/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Sourcegraph. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

'use strict';

/**
 * When an editorActionInvoked event is logged, Action IDs listed here will
 * be elevated and logged as first-class events. The original event will not be logged.
 */
export const EAI_ACTION_IDS_TO_ELEVATE = [
	// Go to definition
	'editor.action.goToDeclaration',
	// Peek definition
	'editor.action.previewDeclaration',
	// Find all references
	'editor.action.referenceSearch.trigger',
];

/**
 * Events with labels in the list below will be skipped entirely.
 */
export const EVENTS_TO_SKIP = [
	'workbenchEditorConfiguration',
	'autoSave',
	'activatePlugin',
	'editorOpened',
	'editorClosed',
	'windowOpened',
	'compositeOpen',
	'compositeShown',
	'emacs.cursorDown',
	'emacs.cursorUp',
	'emacs.cursorDown',
	'emacs.cursorUp',
	'emacs.cursorRight',
	'emacs.cursorLeft',
	'emacs.cursorHome',
	'emacs.cursorEnd',
	'emacs.cursorWordRight',
	'emacs.cursorWordLeft',
	'emacs.cursorPageDown',
	'emacs.cursorPageUp',
	'emacs.cursorTop',
	'emacs.cursorBottom',
	'emacs.C-y',
	'emacs.C-w',
	'emacs.C-k',
	'emacs.C-g',
	'emacs.C-l',
	'emacs.M-w',
	'emacs.C-i',
	'emacs.enterMarkMode',
	'emacs.exitMarkMode',
	'perf:invalidTimers',
	'perf:jsFileSize',
	'registerReviewProvider',
	'searchResultChosen',
	'searchResultsFirstRender',
	'searchResultsFinished',
	'openAnything',
	'shutdown',
	'registerSCMProvider',
	'findReferences',
	'suggestWidget',
	'saveParticipantStats',
	'cachedDataInfo',
	'extensionsScanned',
	'apiUsage',
	'previewHtml',
	'resolvingInput',
	'disposingInput',
	'fileGet',
	'filePUT',
	'UnhandledError',
];

/**
 * When a workbenchActionExecuted event occurs, Action IDs listed here will
 * be skipped entirely.
 */
export const WBA_ACTION_IDS_TO_SKIP = [
	'_moveTo',
	'_moveToSelect',
	'columnSelect',
	'cursorColumnSelectLeft',
	'cursorColumnSelectRight',
	'cursorColumnSelectUp',
	'cursorColumnSelectPageUp',
	'cursorColumnSelectDown',
	'cursorColumnSelectPageDown',
	'cursorMove',
	'cursorLeft',
	'cursorLeftSelect',
	'cursorRight',
	'cursorRightSelect',
	'cursorUp',
	'cursorUpSelect',
	'cursorPageUp',
	'cursorPageUpSelect',
	'cursorDown',
	'cursorDownSelect',
	'cursorPageDown',
	'cursorPageDownSelect',
	'createCursor',
	'_lastCursorMoveToSelect',
	'cursorHome',
	'cursorHomeSelect',
	'cursorLineStart',
	'cursorEnd',
	'cursorEndSelect',
	'cursorLineEnd',
	'cursorTop',
	'cursorTopSelect',
	'cursorBottom',
	'cursorBottomSelect',
	'editorScroll',
	'scrollLineUp',
	'scrollPageUp',
	'scrollLineDown',
	'scrollPageDown',
	'_wordSelect',
	'_wordSelectDrag',
	'lastCursorWordSelect',
	'_lineSelect',
	'_lineSelectDrag',
	'lastCursorLineSelect',
	'lastCursorLineSelectDrag',
	'expandLineSelection',
	'cancelSelection',
	'removeSecondaryCursors',
	'revealLine',
	'selectAll',
	'setSelection',
	'lineBreakInsert',
	'outdent',
	'tab',
	'deleteLeft',
	'deleteRight',
	'editor.action.selectAll',
	'emacs.cursorDown',
	'emacs.cursorUp',
	'emacs.cursorUp',
	'emacs.cursorRight',
	'emacs.cursorLeft',
	'emacs.cursorEnd',
	'emacs.cursorHome',
	'emacs.cursorWordRight',
	'emacs.cursorWordLeft',
	'emacs.enterMarkMode',
	'emacs.cursorPageDown',
	'emacs.cursorPageUp',
	'emacs.C-y',
	'emacs.exitMarkMode',
	'emacs.C-w',
	'emacs.C-g',
	'emacs.C-k',
	'emacs.M-w',
	'emacs.C-l',
	'emacs.C-/',
	'emacs.cursorTop',
	'emacs.cursorBottom',
	'emacs.C-x_C-o',
];
